### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by NedkoBrymchev** [TheoremReach/AndroidSDK#7]
Hello, I am facing strange crash with the latest version 3.4.6. Do you have any suggestions?

Here is the stack trace:

> Caused by android.util.AndroidRuntimeException: Window feature must be requested before adding content
       at androidx.appcompat.app.AppCompatDelegateImpl.throwFeatureRequestIfSubDecorInstalled(AppCompatDelegateImpl.java:2324)
       at androidx.appcompat.app.AppCompatDelegateImpl.requestWindowFeature(AppCompatDelegateImpl.java:1082)
       at androidx.appcompat.app.AppCompatActivity.supportRequestWindowFeature(AppCompatActivity.java:303)
       at theoremreach.com.theoremreach.RewardCenterActivity.onCreate(RewardCenterActivity.java:60)
       at android.app.Activity.performCreate(Activity.java:7967)
       at android.app.Activity.performCreate(Activity.java:7956)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3497)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3665)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)

**Comment by NedkoBrymchev** [comment]
Please take a look. Found the reason but the crash is bad because it is happening on opening TheoremReach. 
When updating androidx.fragment:fragment-ktx:1.4.1 to 1.5.0, it results in the crash above. Not sure what is changed in the update, for now I downgrade it, but it would be nice if you can make it compatible with the newest version.
